FROM cubetiq/calpine-node:latest
LABEL maintainer="sombochea@cubetiqs.com"

RUN apk update && apk add --no-cache git

COPY entrypoint.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]

CMD [ "node" ]