FROM node:20-alpine
LABEL maintainer="sombochea@cubetiqs.com"

# Update NPM package
RUN npm install -g npm@latest

# Checking packages version
RUN echo "NODE: $(node --version)" \
  && echo "NPM: $(npm --version)" \
  && echo "NPX: $(npx --version)"

COPY entrypoint.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]

CMD [ "node" ]
